# Work Experience {-}

**Aquafort AI Marine Biologist **

Starting in late 2020, I was brought on as one of the Marine Biologist for the Newfoundland-based tech startup [Aquafort AI](https://aquafort.ai/). Aquafort AI is an aquaculture technology company aiming to transform the global aquaculture production process and fortify global food security. As their Marine Biologist intern, I've performed literature reviews, consulted on general biological processes and topics, and contact various organizations.




**Biology Department of Memorial University's Quantitative Skills for Biology Guide** 

As more biology-relevant skills become easily performed using computers (statistical analyses, mathematical modelling, managing and reformatting data, etc.) Memorial University is increasing the focus of quantitative skills and best practices throughout its Biology curriculum. As quantitative skills are introduced into various classes, as part of a team, I have contributed to creating the [Quantiative skills for biology guide](https://ahurford.github.io/quant-guide-all-courses/) and several specific course bookdown websites (Principles of Biology [BIOL 1001](https://ahurford.github.io/BIOL-1001/) & [BIOL1002](https://jakep962.github.io/Biol_1002/), [Ecology](https://jakep962.github.io/biol_2600_bookdown/)). 



# Publications, Presentations, and Involvement {.unnumbered}

**Publications**

</br>

</br>

</br>

**Presentations**

-   Biology Graduate Student Symposium Poster Presentation 2021

-   Memorial University Biology Graduate Student Association Work in Progress Seminar Series 2021

-   Science Atlantic Environmental Conference 2019

-   University of New Brunswick Saint John Honours Research 2019

</br>

</br>

**Involvement**

-   Memorial University Biology Graduate Student Association Communication Coordinator 2019-Current

-   Canadian Student Statistical Conference Skills Session Co-chair 2018-2019

-   Statistical and Applied Mathematical Sciences Institute Workshop 2019

-   University of New Brunswick Undergrad Statistical Society Vice President 2018-2019

</br>

</br>

**Awards**

-   University of New Brunswick Student Leadership Award 2019

</br>

</br>
